name: Ruby Gem


on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.0'
    - name: Install dependencies
      run: |
        gem install bundler
        gem install faraday-retry
         gem update bundler
        gem install mustermann
        bundle install
      
        

       
        bundle update mustermann
        gem install webrick
        
    - name: Run tests
      run: bundle exec rspec
    -  run: bundle exec ruby template_server.rb -o 0.0.0.0




